// Auto-generated by scripts/registry_generator.js - DO NOT EDIT MANUALLY
#pragma once

#include <string>
#include <vector>
#include <unordered_map>

namespace ABDJUNiO601 {

struct ParameterSpec {
    const char* id;
    const char* name;
    float minValue;
    float maxValue;
    float defaultValue;
    bool isInteger;
};

inline const std::vector<ParameterSpec>& getParameterRegistry() {
    static const std::vector<ParameterSpec> registry = {
        { "master_volume", "Master Volume", 0.00f, 1.00f, 0.80f, false },
        { "dco_saw", "DCO Sawtooth", 0.00f, 1.00f, 1.00f, false },
        { "dco_pulse", "DCO Pulse/PWM", 0.00f, 1.00f, 0.00f, false },
        { "dco_sub", "DCO Sub Oscillator", 0.00f, 1.00f, 0.00f, false },
        { "dco_noise", "DCO Noise Level", 0.00f, 1.00f, 0.00f, false },
        { "dco_pwm_mod", "DCO PWM Modulation", 0.00f, 1.00f, 0.50f, false },
        { "dco_pwm_mode", "DCO PWM Mode", 0.00f, 1.00f, 0.00f, true },
        { "dco_lfo_mod", "DCO LFO Modulation", 0.00f, 1.00f, 0.00f, false },
        { "vcf_cutoff", "VCF Cutoff Frequency", 0.00f, 1.00f, 0.50f, false },
        { "vcf_resonance", "VCF Resonance", 0.00f, 1.00f, 0.00f, false },
        { "vcf_env_mod", "VCF Envelope Modulation", 0.00f, 1.00f, 0.00f, false },
        { "vcf_lfo_mod", "VCF LFO Modulation", 0.00f, 1.00f, 0.00f, false },
        { "vcf_kybd_mod", "VCF Keyboard Tracking", 0.00f, 1.00f, 0.00f, false },
        { "vcf_hpf", "HPF Cutoff Frequency", 0.00f, 3.00f, 0.00f, true },
        { "vca_mode", "VCA Mode", 0.00f, 1.00f, 0.00f, true },
        { "vca_level", "VCA Level", 0.00f, 1.00f, 0.80f, false },
        { "env_attack", "Envelope Attack", 0.00f, 1.00f, 0.01f, false },
        { "env_decay", "Envelope Decay", 0.00f, 1.00f, 0.30f, false },
        { "env_sustain", "Envelope Sustain", 0.00f, 1.00f, 0.70f, false },
        { "env_release", "Envelope Release", 0.00f, 1.00f, 0.20f, false },
        { "lfo_rate", "LFO Rate", 0.00f, 1.00f, 0.30f, false },
        { "lfo_delay", "LFO Delay Time", 0.00f, 1.00f, 0.00f, false },
        { "chorus_mode", "BBD Chorus Mode", 0.00f, 3.00f, 0.00f, true }
    };
    return registry;
}

} // namespace ABDJUNiO601
