#pragma once

#include <cstddef>
#include <vector>
#include <JuceHeader.h>

#include "J106DACHzTable.h"

/**
 * DacHzTable — Runtime loader for the kV4Hz DAC frequency table.
 *
 * On first call to getDacHzTable(), this loader tries to read the raw
 * binary file "kV4Hz.bin" from the directory containing the current
 * executable.  If the file is not found or the size is wrong, it falls
 * back to the compile-time constexpr array kr106::kV4Hz.
 *
 * The binary file is 4096 doubles = 32768 bytes, generated by
 *   python scripts/generate_dac_bin.py
 *
 * CSV import/export (CalibrationSettings::importDacTableCsv etc.) is
 * unaffected — the customDacTable override still takes priority.
 */
namespace dac_hz_detail {

// C++11 thread-safe static initialiser — the compiler generates a guard
// variable so this lambda runs exactly once even under concurrent calls.
inline const double* loadDacHzTable() noexcept
{
    static const double* s_table = []() -> const double* {
        // Try to load from binary file next to the executable
        const auto exeDir = juce::File::getSpecialLocation(
            juce::File::currentExecutableFile).getParentDirectory();
        const auto binFile = exeDir.getChildFile("kV4Hz.bin");

        if (binFile.existsAsFile())
        {
            juce::FileInputStream stream(binFile);
            if (stream.openedOk())
            {
                const auto fileSize = stream.getTotalLength();
                if (fileSize == static_cast<juce::int64>(kr106::kV4HzSize) *
                                static_cast<juce::int64>(sizeof(double)))
                {
                    static std::vector<double> s_loaded(kr106::kV4HzSize);
                    const auto read = stream.read(s_loaded.data(), fileSize);
                    if (read == fileSize)
                        return s_loaded.data();
                }
            }
        }

        // Fallback: use the compile-time constexpr table
        return kr106::kV4Hz;
    }();

    return s_table;
}

} // namespace dac_hz_detail

/** Returns a pointer to the 4096-element double DAC→Hz lookup table.
 *  Thread-safe (C++11 static init). */
inline const double* getDacHzTable() noexcept
{
    return dac_hz_detail::loadDacHzTable();
}

/** Returns the size of the DAC→Hz table (always 4096). */
inline constexpr std::size_t getDacHzTableSize() noexcept
{
    return kr106::kV4HzSize;
}
