// Source/Synth/JunoADSR.h
#pragma once



/**
 * JunoADSR - Authentic Juno-106 ADSR Envelope
 * 
 * CHARACTERISTICS:
 * - Exponential Curves - Matches the Juno-106's software-generated envelopes.
 * - Software Snappiness: The original Juno-106 envelopes were generated by the on-board MCU,
 *   providing distinct exponential shapes that are "snappy" but musically smooth.
 * - GATE mode support: When the VCA is in GATE mode, the envelope is bypassed/simplified.
 * 
 * IMPLEMENTATION:
 * - State machine: Idle, Attack, Decay, Sustain, Release.
 * - Attack is 1 - exp(-t/tau) [Logarithmic rise].
 * - Decay/Release are exp(-t/tau) [Exponential fall].
 */
class JunoADSR {
public:
    enum class Stage {
        Idle,
        Attack,
        Decay,
        Sustain,
        Release
    };
    
    JunoADSR();
    
    // Setup
    void setSampleRate(double sampleRate);
    void reset();
    
    // Parameters (seconds)
    void setAttack(float seconds);
    void setDecay(float seconds);
    void setSustain(float level);      // 0-1
    void setRelease(float seconds);
    
    // ROM table indices / Raw slider setters
    void setAttackRaw(float slider);
    void setDecayRaw(float slider);
    void setReleaseRaw(float slider);
    void setTimeScale(float scale) { mTimeScale = scale; calculateRates(); }
    
    void setGateMode(bool enabled);    // ENV button
    void setSlewMs(float ms);         // [Calibration] Dynamic smoothing
    void setAttackFactor(float factor); 
    void setMcuRate(float ms) { mcuRateFactor = ms; calculateRates(); }
    void setDacSteps(float steps) { dacSteps = steps; }
    void setOvershoot(float level) { overshoot = level; }
    
    // Lifecycle
    void noteOn();
    void noteOff();
    
    // Processing
    float getNextSample();
    bool isActive() const { return stage != Stage::Idle; }
    
    Stage getCurrentStage() const { return stage; }
    float getCurrentValue() const { return currentValue; }
    
private:
    static constexpr uint16_t kEnvMax = 0x3FFF;
    double sampleRate = 44100.0;
    
    // Parameters
    float attackTime = 0.01f;      // seconds
    float decayTime = 0.3f;        // seconds
    float sustainLevel = 0.7f;     // 0-1
    float releaseTime = 0.5f;      // seconds
    bool gateMode = false;         // ENV button state
    float slewMs = 1.5f;           // [Calibration] Output smoothing time
    float attackFactor = 0.35f;    // [Calibration] Attack curvature
    float mcuRateFactor = 4.2335f; // [Calibration] MCU update speed (ms)
    float dacSteps = 1024.0f;      // [Calibration] DAC resolution (steps)
    float overshoot = 1.08f;       // [Calibration] Attack overshoot target
    
    // State
    Stage stage = Stage::Idle;
    float currentValue = 0.0f;
    
    // [Fidelidad] MCU Emulation & Ticks
    uint16_t mEnvInt = 0;        // current 14-bit envelope (0–0x3FFF)
    uint16_t mAtkInc = 0;        // attack increment per tick
    uint16_t mDecMul = 0;        // decay multiplier per tick
    uint16_t mRelMul = 0;        // release multiplier per tick
    uint16_t mSusInt = 0;        // sustain level as integer
    float mTickAccum = 0.f;      // fractional tick accumulator
    float mEnvPrev = 0.f;        // previous tick output (for interpolation)
    float mEnvNext = 0.f;        // current tick output (for interpolation)
    float mTickStep = 0.f;       // ticks per sample
    float mTimeScale = 1.0f;     // per-voice component tolerance
    
    float smoothedValue = 0.0f; 
    
    // Helpers
    void calculateRates();
    void tick106();
    static uint16_t calcDecay(uint16_t value, uint16_t coeff);
};
