/**
 * Parameter Registry Generator for ABDJUNiO601
 * Central source of truth generating:
 *  - Source/Core/ParameterRegistry.gen.h
 *  - WebUI/js/registry.gen.js
 *  - schemas/parameter-registry.data.json
 */

const fs = require('fs');
const path = require('path');

const rootDir = path.resolve(__dirname, '..');

const parameters = [
  { id: 'master_volume', name: 'Master Volume', min: 0.0, max: 1.0, default: 0.8, type: 'float' },
  { id: 'dco_saw', name: 'DCO Sawtooth', min: 0.0, max: 1.0, default: 1.0, type: 'float' },
  { id: 'dco_pulse', name: 'DCO Pulse/PWM', min: 0.0, max: 1.0, default: 0.0, type: 'float' },
  { id: 'dco_sub', name: 'DCO Sub Oscillator', min: 0.0, max: 1.0, default: 0.0, type: 'float' },
  { id: 'dco_noise', name: 'DCO Noise Level', min: 0.0, max: 1.0, default: 0.0, type: 'float' },
  { id: 'dco_pwm_mod', name: 'DCO PWM Modulation', min: 0.0, max: 1.0, default: 0.5, type: 'float' },
  { id: 'dco_pwm_mode', name: 'DCO PWM Mode', min: 0, max: 1, default: 0, type: 'int' }, // 0: LFO, 1: Manual
  { id: 'dco_lfo_mod', name: 'DCO LFO Modulation', min: 0.0, max: 1.0, default: 0.0, type: 'float' },
  { id: 'vcf_cutoff', name: 'VCF Cutoff Frequency', min: 0.0, max: 1.0, default: 0.5, type: 'float' },
  { id: 'vcf_resonance', name: 'VCF Resonance', min: 0.0, max: 1.0, default: 0.0, type: 'float' },
  { id: 'vcf_env_mod', name: 'VCF Envelope Modulation', min: 0.0, max: 1.0, default: 0.0, type: 'float' },
  { id: 'vcf_lfo_mod', name: 'VCF LFO Modulation', min: 0.0, max: 1.0, default: 0.0, type: 'float' },
  { id: 'vcf_kybd_mod', name: 'VCF Keyboard Tracking', min: 0.0, max: 1.0, default: 0.0, type: 'float' },
  { id: 'vcf_hpf', name: 'HPF Cutoff Frequency', min: 0, max: 3, default: 0, type: 'int' },
  { id: 'vca_mode', name: 'VCA Mode', min: 0, max: 1, default: 0, type: 'int' }, // 0: ENV, 1: GATE
  { id: 'vca_level', name: 'VCA Level', min: 0.0, max: 1.0, default: 0.8, type: 'float' },
  { id: 'env_attack', name: 'Envelope Attack', min: 0.0, max: 1.0, default: 0.01, type: 'float' },
  { id: 'env_decay', name: 'Envelope Decay', min: 0.0, max: 1.0, default: 0.3, type: 'float' },
  { id: 'env_sustain', name: 'Envelope Sustain', min: 0.0, max: 1.0, default: 0.7, type: 'float' },
  { id: 'env_release', name: 'Envelope Release', min: 0.0, max: 1.0, default: 0.2, type: 'float' },
  { id: 'lfo_rate', name: 'LFO Rate', min: 0.0, max: 1.0, default: 0.3, type: 'float' },
  { id: 'lfo_delay', name: 'LFO Delay Time', min: 0.0, max: 1.0, default: 0.0, type: 'float' },
  { id: 'chorus_mode', name: 'BBD Chorus Mode', min: 0, max: 3, default: 0, type: 'int' } // 0: Off, 1: Mode I, 2: Mode II, 3: Mode I+II
];

function generateCppHeader() {
  const headerContent = `// Auto-generated by scripts/registry_generator.js - DO NOT EDIT MANUALLY
#pragma once

#include <string>
#include <vector>
#include <unordered_map>

namespace ABDJUNiO601 {

struct ParameterSpec {
    const char* id;
    const char* name;
    float minValue;
    float maxValue;
    float defaultValue;
    bool isInteger;
};

inline const std::vector<ParameterSpec>& getParameterRegistry() {
    static const std::vector<ParameterSpec> registry = {
${parameters.map(p => `        { "${p.id}", "${p.name}", ${p.min.toFixed(2)}f, ${p.max.toFixed(2)}f, ${p.default.toFixed(2)}f, ${p.type === 'int' ? 'true' : 'false'} }`).join(',\n')}
    };
    return registry;
}

} // namespace ABDJUNiO601
`;

  const headerPath = path.join(rootDir, 'Source', 'Core', 'ParameterRegistry.gen.h');
  fs.writeFileSync(headerPath, headerContent, 'utf-8');
  console.log(`Generated: ${headerPath}`);
}

function generateJsRegistry() {
  const jsContent = `// Auto-generated by scripts/registry_generator.js - DO NOT EDIT MANUALLY

export const PARAMETER_REGISTRY = ${JSON.stringify(parameters, null, 2)};

export const PARAMETER_MAP = Object.fromEntries(
  PARAMETER_REGISTRY.map(p => [p.id, p])
);

export function normalizeValue(id, rawValue) {
  const spec = PARAMETER_MAP[id];
  if (!spec) return rawValue;
  return (rawValue - spec.min) / (spec.max - spec.min);
}

export function denormalizeValue(id, normalizedValue) {
  const spec = PARAMETER_MAP[id];
  if (!spec) return normalizedValue;
  const raw = spec.min + normalizedValue * (spec.max - spec.min);
  return spec.type === 'int' ? Math.round(raw) : raw;
}
`;

  const jsPath = path.join(rootDir, 'WebUI', 'js', 'registry.gen.js');
  fs.writeFileSync(jsPath, jsContent, 'utf-8');
  console.log(`Generated: ${jsPath}`);
}

function generateJsonSchema() {
  const schema = {
    $schema: "http://json-schema.org/draft-07/schema#",
    title: "ABDJUNiO601 Parameter Registry Schema",
    version: "1.0.0",
    type: "object",
    properties: {
      parameters: {
        type: "array",
        items: {
          type: "object",
          properties: {
            id: { type: "string" },
            name: { type: "string" },
            min: { type: "number" },
            max: { type: "number" },
            default: { type: "number" },
            type: { type: "string", enum: ["float", "int"] }
          },
          required: ["id", "name", "min", "max", "default", "type"]
        }
      }
    },
    data: { parameters }
  };

  const schemaPath = path.join(rootDir, 'schemas', 'parameter-registry.data.json');
  fs.writeFileSync(schemaPath, JSON.stringify(schema, null, 2), 'utf-8');
  console.log(`Generated: ${schemaPath}`);
}

generateCppHeader();
generateJsRegistry();
generateJsonSchema();
